"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Bell, AlertTriangle, AlertCircle, Info, Check } from "lucide-react";
import api from "@/lib/api";

/**
 * The dashboard alert feed.
 *
 * Every owner alert this system raises (critical stock, out of stock, late
 * supplier, slow day, failed M-Pesa payment, morning briefing) used to go out
 * over WhatsApp only — so a deployment without a configured Twilio sender, which
 * is the normal state before one is approved, raised alerts that reached nobody.
 * This bell is the delivery channel that has no external dependency and so
 * cannot silently fail.
 */

type Notification = {
    id: number;
    category: string;
    severity: "info" | "warning" | "critical";
    title: string;
    body: string;
    link: string;
    read_at: string | null;
    created_at: string | null;
};

// Poll rather than push: the backend has no websocket layer, and a 60s interval
// is well inside the useful latency for alerts that are themselves generated by
// a scheduler running every couple of hours.
const POLL_MS = 60_000;

const SEVERITY_STYLES: Record<string, { icon: typeof Info; color: string }> = {
    critical: { icon: AlertCircle, color: "text-red-400" },
    warning: { icon: AlertTriangle, color: "text-[#d4a853]" },
    info: { icon: Info, color: "text-[#737373]" },
};

function timeAgo(iso: string | null): string {
    if (!iso) return "";
    // Backend timestamps are UTC but serialise without a zone designator, so
    // Date would read them as local time and show "in 3 hours" for something
    // that just happened. Append Z when there is no offset already.
    const normalised = /[Z+]|-\d{2}:\d{2}$/.test(iso) ? iso : `${iso}Z`;
    const seconds = (Date.now() - new Date(normalised).getTime()) / 1000;
    if (seconds < 60) return "just now";
    if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`;
    if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`;
    return `${Math.floor(seconds / 86400)}d ago`;
}

export default function NotificationBell() {
    const router = useRouter();
    const [items, setItems] = useState<Notification[]>([]);
    const [unread, setUnread] = useState(0);
    const [open, setOpen] = useState(false);
    const panelRef = useRef<HTMLDivElement>(null);

    const load = useCallback(async () => {
        try {
            const res = await api.get("/api/v1/notifications/", { params: { limit: 30 } });
            setItems(res.data.items ?? []);
            setUnread(res.data.unread ?? 0);
        } catch {
            // A failed poll must never break the dashboard chrome around it —
            // the bell simply keeps showing the last good state.
        }
    }, []);

    useEffect(() => {
        load();
        const id = setInterval(load, POLL_MS);
        return () => clearInterval(id);
    }, [load]);

    // Close on outside click and on Escape, so the panel never traps the page.
    useEffect(() => {
        if (!open) return;
        const onClick = (e: MouseEvent) => {
            if (panelRef.current && !panelRef.current.contains(e.target as Node)) setOpen(false);
        };
        const onKey = (e: KeyboardEvent) => {
            if (e.key === "Escape") setOpen(false);
        };
        document.addEventListener("mousedown", onClick);
        document.addEventListener("keydown", onKey);
        return () => {
            document.removeEventListener("mousedown", onClick);
            document.removeEventListener("keydown", onKey);
        };
    }, [open]);

    const markRead = async (id: number) => {
        // Optimistic: the badge should drop the instant it is clicked. Reconciled
        // by the server's authoritative count below, and by the next poll.
        setItems((prev) =>
            prev.map((n) => (n.id === id ? { ...n, read_at: new Date().toISOString() } : n))
        );
        setUnread((u) => Math.max(0, u - 1));
        try {
            const res = await api.post(`/api/v1/notifications/${id}/read`);
            setUnread(res.data.unread);
        } catch {
            load();
        }
    };

    const markAllRead = async () => {
        setItems((prev) => prev.map((n) => ({ ...n, read_at: n.read_at ?? new Date().toISOString() })));
        setUnread(0);
        try {
            await api.post("/api/v1/notifications/read-all");
        } catch {
            load();
        }
    };

    const openNotification = (n: Notification) => {
        if (!n.read_at) markRead(n.id);
        if (n.link) {
            setOpen(false);
            router.push(n.link);
        }
    };

    return (
        <div className="relative" ref={panelRef}>
            <button
                onClick={() => setOpen((o) => !o)}
                aria-label={unread > 0 ? `Alerts, ${unread} unread` : "Alerts"}
                className="relative text-[#737373] hover:text-[#e5e5e5] transition-colors p-1"
            >
                <Bell className="w-5 h-5" />
                {unread > 0 && (
                    <span className="absolute -top-0.5 -right-0.5 min-w-[16px] h-4 px-1 flex items-center justify-center rounded-full bg-red-500 text-[10px] font-bold text-white">
                        {unread > 9 ? "9+" : unread}
                    </span>
                )}
            </button>

            {open && (
                <div className="absolute right-0 mt-2 w-[min(22rem,calc(100vw-2rem))] max-h-[26rem] overflow-y-auto rounded-lg border border-[#1a1a1a] bg-[#0f0f0f] shadow-xl z-50">
                    <div className="sticky top-0 flex items-center justify-between px-4 py-3 border-b border-[#1a1a1a] bg-[#0f0f0f]">
                        <span className="text-sm font-semibold text-[#e5e5e5]">Alerts</span>
                        {unread > 0 && (
                            <button
                                onClick={markAllRead}
                                className="flex items-center gap-1 text-xs text-[#737373] hover:text-[#d4a853] transition-colors"
                            >
                                <Check className="w-3 h-3" />
                                Mark all read
                            </button>
                        )}
                    </div>

                    {items.length === 0 ? (
                        <p className="px-4 py-8 text-center text-sm text-[#525252]">
                            No alerts yet. Stock warnings and daily briefings show up here.
                        </p>
                    ) : (
                        <ul>
                            {items.map((n) => {
                                const style = SEVERITY_STYLES[n.severity] ?? SEVERITY_STYLES.info;
                                const Icon = style.icon;
                                return (
                                    <li key={n.id}>
                                        <button
                                            onClick={() => openNotification(n)}
                                            className={`w-full text-left flex gap-3 px-4 py-3 border-b border-[#141414] hover:bg-[#141414] transition-colors ${
                                                n.read_at ? "opacity-60" : ""
                                            }`}
                                        >
                                            <Icon className={`w-4 h-4 mt-0.5 shrink-0 ${style.color}`} />
                                            <span className="min-w-0 flex-1">
                                                <span className="block text-sm font-medium text-[#e5e5e5] break-words">
                                                    {n.title}
                                                </span>
                                                {n.body && (
                                                    <span className="block text-xs text-[#737373] mt-0.5 line-clamp-3 whitespace-pre-line break-words">
                                                        {n.body}
                                                    </span>
                                                )}
                                                <span className="block text-[10px] text-[#525252] mt-1">
                                                    {timeAgo(n.created_at)}
                                                </span>
                                            </span>
                                            {!n.read_at && (
                                                <span className="w-1.5 h-1.5 rounded-full bg-[#d4a853] mt-1.5 shrink-0" />
                                            )}
                                        </button>
                                    </li>
                                );
                            })}
                        </ul>
                    )}
                </div>
            )}
        </div>
    );
}
