"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Bell, AlertTriangle, AlertCircle, Info, Check, Settings, ArrowLeft, Lock } from "lucide-react";
import api from "@/lib/api";

/**
 * The dashboard alert feed.
 *
 * Every owner alert this system raises (critical stock, out of stock, late
 * supplier, slow day, failed M-Pesa payment, morning briefing) used to go out
 * over WhatsApp only — so a deployment without a configured Twilio sender, which
 * is the normal state before one is approved, raised alerts that reached nobody.
 * This bell is the delivery channel that has no external dependency and so
 * cannot silently fail.
 */

type Preference = {
    category: string;
    label: string;
    mutable: boolean;   // false = an alert too important to silence
    muted: boolean;
};

type Notification = {
    id: number;
    category: string;
    severity: "info" | "warning" | "critical";
    title: string;
    body: string;
    link: string;
    read_at: string | null;
    created_at: string | null;
};

// Poll rather than push: the backend has no websocket layer, and a 60s interval
// is well inside the useful latency for alerts that are themselves generated by
// a scheduler running every couple of hours.
const POLL_MS = 60_000;

const SEVERITY_STYLES: Record<string, { icon: typeof Info; color: string }> = {
    critical: { icon: AlertCircle, color: "text-red-400" },
    warning: { icon: AlertTriangle, color: "text-[#d4a853]" },
    info: { icon: Info, color: "text-[#737373]" },
};

function timeAgo(iso: string | null): string {
    if (!iso) return "";
    // Backend timestamps are UTC but serialise without a zone designator, so
    // Date would read them as local time and show "in 3 hours" for something
    // that just happened. Append Z when there is no offset already.
    const normalised = /[Z+]|-\d{2}:\d{2}$/.test(iso) ? iso : `${iso}Z`;
    const seconds = (Date.now() - new Date(normalised).getTime()) / 1000;
    if (seconds < 60) return "just now";
    if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`;
    if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`;
    return `${Math.floor(seconds / 86400)}d ago`;
}

export default function NotificationBell() {
    const router = useRouter();
    const [items, setItems] = useState<Notification[]>([]);
    const [unread, setUnread] = useState(0);
    const [open, setOpen] = useState(false);
    // The panel is either the feed or the settings list, never both — at this
    // width a split view would leave neither usable.
    const [showSettings, setShowSettings] = useState(false);
    const [prefs, setPrefs] = useState<Preference[]>([]);
    const panelRef = useRef<HTMLDivElement>(null);

    const load = useCallback(async () => {
        try {
            const res = await api.get("/api/v1/notifications/", { params: { limit: 30 } });
            setItems(res.data.items ?? []);
            setUnread(res.data.unread ?? 0);
        } catch {
            // A failed poll must never break the dashboard chrome around it —
            // the bell simply keeps showing the last good state.
        }
    }, []);

    useEffect(() => {
        load();
        const id = setInterval(load, POLL_MS);
        return () => clearInterval(id);
    }, [load]);

    // Close on outside click and on Escape, so the panel never traps the page.
    useEffect(() => {
        if (!open) return;
        const onClick = (e: MouseEvent) => {
            if (panelRef.current && !panelRef.current.contains(e.target as Node)) setOpen(false);
        };
        const onKey = (e: KeyboardEvent) => {
            if (e.key === "Escape") setOpen(false);
        };
        document.addEventListener("mousedown", onClick);
        document.addEventListener("keydown", onKey);
        return () => {
            document.removeEventListener("mousedown", onClick);
            document.removeEventListener("keydown", onKey);
        };
    }, [open]);

    const loadPrefs = useCallback(async () => {
        try {
            const res = await api.get("/api/v1/notifications/preferences");
            setPrefs(res.data.items ?? []);
        } catch {
            setPrefs([]);
        }
    }, []);

    const openSettings = () => {
        setShowSettings(true);
        loadPrefs();
    };

    const toggleMute = async (category: string) => {
        const next = prefs.map((p) =>
            p.category === category ? { ...p, muted: !p.muted } : p
        );
        setPrefs(next);                                   // optimistic
        try {
            const res = await api.put("/api/v1/notifications/preferences", {
                muted: next.filter((p) => p.muted).map((p) => p.category),
            });
            // The server is authoritative — it drops anything unmutable, so a
            // switch that could not really be flipped snaps back here.
            setPrefs(res.data.items ?? next);
            load();                                       // badge reflects the change
        } catch {
            loadPrefs();
        }
    };

    const markRead = async (id: number) => {
        // Optimistic: the badge should drop the instant it is clicked. Reconciled
        // by the server's authoritative count below, and by the next poll.
        setItems((prev) =>
            prev.map((n) => (n.id === id ? { ...n, read_at: new Date().toISOString() } : n))
        );
        setUnread((u) => Math.max(0, u - 1));
        try {
            const res = await api.post(`/api/v1/notifications/${id}/read`);
            setUnread(res.data.unread);
        } catch {
            load();
        }
    };

    const markAllRead = async () => {
        setItems((prev) => prev.map((n) => ({ ...n, read_at: n.read_at ?? new Date().toISOString() })));
        setUnread(0);
        try {
            await api.post("/api/v1/notifications/read-all");
        } catch {
            load();
        }
    };

    const openNotification = (n: Notification) => {
        if (!n.read_at) markRead(n.id);
        // Only ever navigate to an in-app path. Links are set server-side from
        // hardcoded strings today, but this is a value read from the database and
        // pushed into the router — refusing anything that isn't a single-slash
        // relative path keeps that from becoming an open redirect if the column
        // is ever populated from somewhere less controlled. `//evil.com` is
        // protocol-relative, hence the second character check.
        if (n.link.startsWith("/") && !n.link.startsWith("//")) {
            setOpen(false);
            router.push(n.link);
        }
    };

    return (
        <div className="relative" ref={panelRef}>
            <button
                onClick={() => {
                    // Always reopen on the feed. Settings is somewhere you visit
                    // and leave; landing back on it later, having forgotten you
                    // were there, reads as the alerts having disappeared.
                    setShowSettings(false);
                    setOpen((o) => !o);
                }}
                aria-label={unread > 0 ? `Alerts, ${unread} unread` : "Alerts"}
                className="relative text-[#737373] hover:text-[#e5e5e5] transition-colors p-1"
            >
                <Bell className="w-5 h-5" />
                {unread > 0 && (
                    <span className="absolute -top-0.5 -right-0.5 min-w-[16px] h-4 px-1 flex items-center justify-center rounded-full bg-red-500 text-[10px] font-bold text-white">
                        {unread > 9 ? "9+" : unread}
                    </span>
                )}
            </button>

            {open && (
                <div className="absolute right-0 mt-2 w-[min(22rem,calc(100vw-2rem))] max-h-[26rem] overflow-y-auto rounded-lg border border-[#1a1a1a] bg-[#0f0f0f] shadow-xl z-50">
                    <div className="sticky top-0 flex items-center justify-between px-4 py-3 border-b border-[#1a1a1a] bg-[#0f0f0f]">
                        <span className="flex items-center gap-2 text-sm font-semibold text-[#e5e5e5]">
                            {showSettings && (
                                <button
                                    onClick={() => setShowSettings(false)}
                                    aria-label="Back to alerts"
                                    className="text-[#737373] hover:text-[#e5e5e5]"
                                >
                                    <ArrowLeft className="w-4 h-4" />
                                </button>
                            )}
                            {showSettings ? "What you get notified about" : "Alerts"}
                        </span>
                        <span className="flex items-center gap-3">
                            {!showSettings && unread > 0 && (
                                <button
                                    onClick={markAllRead}
                                    className="flex items-center gap-1 text-xs text-[#737373] hover:text-[#d4a853] transition-colors"
                                >
                                    <Check className="w-3 h-3" />
                                    Mark all read
                                </button>
                            )}
                            {!showSettings && (
                                <button
                                    onClick={openSettings}
                                    aria-label="Notification settings"
                                    className="text-[#737373] hover:text-[#d4a853] transition-colors"
                                >
                                    <Settings className="w-4 h-4" />
                                </button>
                            )}
                        </span>
                    </div>

                    {showSettings ? (
                        <ul className="py-1">
                            {prefs.map((p) => (
                                <li key={p.category}>
                                    <button
                                        onClick={() => p.mutable && toggleMute(p.category)}
                                        disabled={!p.mutable}
                                        title={p.mutable ? undefined
                                            : "Too important to switch off — you would stop being able to serve"}
                                        className={`w-full flex items-center justify-between gap-3 px-4 py-2.5 text-left transition-colors ${
                                            p.mutable ? "hover:bg-[#141414]" : "cursor-not-allowed"
                                        }`}
                                    >
                                        <span className="flex items-center gap-2 min-w-0">
                                            {!p.mutable && <Lock className="w-3 h-3 shrink-0 text-[#525252]" />}
                                            <span className={`text-sm truncate ${
                                                p.mutable ? "text-[#e5e5e5]" : "text-[#737373]"
                                            }`}>
                                                {p.label}
                                            </span>
                                        </span>
                                        <span
                                            aria-hidden
                                            className={`relative w-8 h-4 rounded-full shrink-0 transition-colors ${
                                                !p.mutable ? "bg-[#2a2a2a]"
                                                    : p.muted ? "bg-[#2a2a2a]" : "bg-[#d4a853]"
                                            }`}
                                        >
                                            <span className={`absolute top-0.5 w-3 h-3 rounded-full bg-[#0f0f0f] transition-all ${
                                                p.muted && p.mutable ? "left-0.5" : "left-4"
                                            }`} />
                                        </span>
                                    </button>
                                </li>
                            ))}
                            <li className="px-4 py-3 text-[11px] leading-relaxed text-[#525252] border-t border-[#141414]">
                                Switching one off only hides it from you. Everyone else still
                                gets it, and it is still recorded.
                            </li>
                        </ul>
                    ) : items.length === 0 ? (
                        <p className="px-4 py-8 text-center text-sm text-[#525252]">
                            No alerts yet. Stock warnings and daily briefings show up here.
                        </p>
                    ) : (
                        <ul>
                            {items.map((n) => {
                                const style = SEVERITY_STYLES[n.severity] ?? SEVERITY_STYLES.info;
                                const Icon = style.icon;
                                return (
                                    <li key={n.id}>
                                        <button
                                            onClick={() => openNotification(n)}
                                            className={`w-full text-left flex gap-3 px-4 py-3 border-b border-[#141414] hover:bg-[#141414] transition-colors ${
                                                n.read_at ? "opacity-60" : ""
                                            }`}
                                        >
                                            <Icon className={`w-4 h-4 mt-0.5 shrink-0 ${style.color}`} />
                                            <span className="min-w-0 flex-1">
                                                <span className="block text-sm font-medium text-[#e5e5e5] break-words">
                                                    {n.title}
                                                </span>
                                                {n.body && (
                                                    <span className="block text-xs text-[#737373] mt-0.5 line-clamp-3 whitespace-pre-line break-words">
                                                        {n.body}
                                                    </span>
                                                )}
                                                <span className="block text-[10px] text-[#525252] mt-1">
                                                    {timeAgo(n.created_at)}
                                                </span>
                                            </span>
                                            {!n.read_at && (
                                                <span className="w-1.5 h-1.5 rounded-full bg-[#d4a853] mt-1.5 shrink-0" />
                                            )}
                                        </button>
                                    </li>
                                );
                            })}
                        </ul>
                    )}
                </div>
            )}
        </div>
    );
}
