"""workspace plans, limits, settings

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-26 12:47:59.438665
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('plan', sa.String(length=20), server_default='internal', nullable=False))
    op.add_column('workspaces', sa.Column('seat_limit', sa.Integer(), nullable=True))
    op.add_column('workspaces', sa.Column('monthly_agent_run_limit', sa.Integer(), nullable=True))
    op.add_column('workspaces', sa.Column('enabled_departments', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workspaces', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'settings')
    op.drop_column('workspaces', 'enabled_departments')
    op.drop_column('workspaces', 'monthly_agent_run_limit')
    op.drop_column('workspaces', 'seat_limit')
    op.drop_column('workspaces', 'plan')
    # ### end Alembic commands ###
