"""department: command

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-26 12:48:01.453621
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmd_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('metric', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('baseline_value', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('target_value', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='on_track', nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cmd_goals_workspace_id'), 'cmd_goals', ['workspace_id'], unique=False)
    op.create_table('cmd_meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('held_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attendees', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cmd_meetings_workspace_id'), 'cmd_meetings', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cmd_meetings_workspace_id'), table_name='cmd_meetings')
    op.drop_table('cmd_meetings')
    op.drop_index(op.f('ix_cmd_goals_workspace_id'), table_name='cmd_goals')
    op.drop_table('cmd_goals')
    # ### end Alembic commands ###
