"""department: delivery

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-26 12:48:06.276746
"""
from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dlv_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='planned', nullable=False),
    sa.Column('start_on', sa.Date(), nullable=True),
    sa.Column('end_on', sa.Date(), nullable=True),
    sa.Column('budget_minor', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('github_repo', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dlv_projects_organization_id'), 'dlv_projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_dlv_projects_workspace_id'), 'dlv_projects', ['workspace_id'], unique=False)
    op.create_table('dlv_change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='requested', nullable=False),
    sa.Column('cost_minor', sa.Integer(), nullable=True),
    sa.Column('days_impact', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['dlv_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dlv_change_requests_project_id'), 'dlv_change_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_dlv_change_requests_workspace_id'), 'dlv_change_requests', ['workspace_id'], unique=False)
    op.create_table('dlv_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='planned', nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=True),
    sa.Column('completed_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['dlv_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dlv_milestones_project_id'), 'dlv_milestones', ['project_id'], unique=False)
    op.create_index(op.f('ix_dlv_milestones_workspace_id'), 'dlv_milestones', ['workspace_id'], unique=False)
    op.create_table('dlv_time_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('worked_on', sa.Date(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('billable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['dlv_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dlv_time_entries_project_id'), 'dlv_time_entries', ['project_id'], unique=False)
    op.create_index(op.f('ix_dlv_time_entries_workspace_id'), 'dlv_time_entries', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dlv_time_entries_workspace_id'), table_name='dlv_time_entries')
    op.drop_index(op.f('ix_dlv_time_entries_project_id'), table_name='dlv_time_entries')
    op.drop_table('dlv_time_entries')
    op.drop_index(op.f('ix_dlv_milestones_workspace_id'), table_name='dlv_milestones')
    op.drop_index(op.f('ix_dlv_milestones_project_id'), table_name='dlv_milestones')
    op.drop_table('dlv_milestones')
    op.drop_index(op.f('ix_dlv_change_requests_workspace_id'), table_name='dlv_change_requests')
    op.drop_index(op.f('ix_dlv_change_requests_project_id'), table_name='dlv_change_requests')
    op.drop_table('dlv_change_requests')
    op.drop_index(op.f('ix_dlv_projects_workspace_id'), table_name='dlv_projects')
    op.drop_index(op.f('ix_dlv_projects_organization_id'), table_name='dlv_projects')
    op.drop_table('dlv_projects')
    # ### end Alembic commands ###
