"""department: finance

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-26 12:56:09.510438
"""
from alembic import op
import sqlalchemy as sa


revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fin_cash_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=100), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('balance_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_cash_snapshots_workspace_id'), 'fin_cash_snapshots', ['workspace_id'], unique=False)
    op.create_table('fin_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('cadence', sa.String(length=20), server_default='monthly', nullable=False),
    sa.Column('next_renewal_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_subscriptions_workspace_id'), 'fin_subscriptions', ['workspace_id'], unique=False)
    op.create_table('fin_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('spent_on', sa.Date(), nullable=False),
    sa.Column('vendor', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('suggested_category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='unconfirmed', nullable=False),
    sa.Column('receipt_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receipt_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_expenses_workspace_id'), 'fin_expenses', ['workspace_id'], unique=False)
    op.create_table('fin_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal_minor', sa.Integer(), nullable=False),
    sa.Column('tax_minor', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_minor', sa.Integer(), nullable=False),
    sa.Column('amount_paid_minor', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('etims_reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reminded_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'number')
    )
    op.create_index(op.f('ix_fin_invoices_organization_id'), 'fin_invoices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_fin_invoices_workspace_id'), 'fin_invoices', ['workspace_id'], unique=False)
    op.create_table('fin_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.String(length=20), server_default='other', nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['fin_invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_payments_invoice_id'), 'fin_payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_fin_payments_workspace_id'), 'fin_payments', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fin_payments_workspace_id'), table_name='fin_payments')
    op.drop_index(op.f('ix_fin_payments_invoice_id'), table_name='fin_payments')
    op.drop_table('fin_payments')
    op.drop_index(op.f('ix_fin_invoices_workspace_id'), table_name='fin_invoices')
    op.drop_index(op.f('ix_fin_invoices_organization_id'), table_name='fin_invoices')
    op.drop_table('fin_invoices')
    op.drop_index(op.f('ix_fin_expenses_workspace_id'), table_name='fin_expenses')
    op.drop_table('fin_expenses')
    op.drop_index(op.f('ix_fin_subscriptions_workspace_id'), table_name='fin_subscriptions')
    op.drop_table('fin_subscriptions')
    op.drop_index(op.f('ix_fin_cash_snapshots_workspace_id'), table_name='fin_cash_snapshots')
    op.drop_table('fin_cash_snapshots')
    # ### end Alembic commands ###
