"""department: legal

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-26 12:56:12.254029
"""
from alembic import op
import sqlalchemy as sa


revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_processing_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='controller', nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('data_categories', sa.Text(), nullable=True),
    sa.Column('data_subjects', sa.Text(), nullable=True),
    sa.Column('lawful_basis', sa.Text(), nullable=True),
    sa.Column('recipients', sa.Text(), nullable=True),
    sa.Column('cross_border', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('retention', sa.Text(), nullable=True),
    sa.Column('security_measures', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=200), nullable=True),
    sa.Column('reviewed_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_processing_activities_workspace_id'), 'legal_processing_activities', ['workspace_id'], unique=False)
    op.create_table('legal_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=20), server_default='other', nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=200), nullable=True),
    sa.Column('reviewed_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_templates_workspace_id'), 'legal_templates', ['workspace_id'], unique=False)
    op.create_table('legal_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), server_default='other', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('signed_on', sa.Date(), nullable=True),
    sa.Column('start_on', sa.Date(), nullable=True),
    sa.Column('end_on', sa.Date(), nullable=True),
    sa.Column('auto_renews', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notice_days', sa.Integer(), nullable=True),
    sa.Column('value_minor', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_contracts_organization_id'), 'legal_contracts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_legal_contracts_workspace_id'), 'legal_contracts', ['workspace_id'], unique=False)
    op.create_table('legal_obligations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('recurrence', sa.String(length=20), server_default='none', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('source_clause', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['legal_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_obligations_contract_id'), 'legal_obligations', ['contract_id'], unique=False)
    op.create_index(op.f('ix_legal_obligations_workspace_id'), 'legal_obligations', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legal_obligations_workspace_id'), table_name='legal_obligations')
    op.drop_index(op.f('ix_legal_obligations_contract_id'), table_name='legal_obligations')
    op.drop_table('legal_obligations')
    op.drop_index(op.f('ix_legal_contracts_workspace_id'), table_name='legal_contracts')
    op.drop_index(op.f('ix_legal_contracts_organization_id'), table_name='legal_contracts')
    op.drop_table('legal_contracts')
    op.drop_index(op.f('ix_legal_templates_workspace_id'), table_name='legal_templates')
    op.drop_table('legal_templates')
    op.drop_index(op.f('ix_legal_processing_activities_workspace_id'), table_name='legal_processing_activities')
    op.drop_table('legal_processing_activities')
    # ### end Alembic commands ###
