"""department: marketing

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-26 12:56:14.910108
"""
from alembic import op
import sqlalchemy as sa


revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mkt_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='planned', nullable=False),
    sa.Column('start_on', sa.Date(), nullable=True),
    sa.Column('end_on', sa.Date(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('budget_minor', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mkt_campaigns_workspace_id'), 'mkt_campaigns', ['workspace_id'], unique=False)
    op.create_table('mkt_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('granted_by', sa.String(length=200), nullable=False),
    sa.Column('granted_on', sa.Date(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('revoked_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mkt_consents_organization_id'), 'mkt_consents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_mkt_consents_workspace_id'), 'mkt_consents', ['workspace_id'], unique=False)
    op.create_table('mkt_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=20), server_default='post', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='idea', nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('publish_on', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['mkt_campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mkt_content_workspace_id'), 'mkt_content', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mkt_content_workspace_id'), table_name='mkt_content')
    op.drop_table('mkt_content')
    op.drop_index(op.f('ix_mkt_consents_workspace_id'), table_name='mkt_consents')
    op.drop_index(op.f('ix_mkt_consents_organization_id'), table_name='mkt_consents')
    op.drop_table('mkt_consents')
    op.drop_index(op.f('ix_mkt_campaigns_workspace_id'), table_name='mkt_campaigns')
    op.drop_table('mkt_campaigns')
    # ### end Alembic commands ###
