"""department: product

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-26 12:56:17.579206
"""
from alembic import op
import sqlalchemy as sa


revision = '0010'
down_revision = '0009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prd_roadmap_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='idea', nullable=False),
    sa.Column('target_quarter', sa.String(length=7), nullable=True),
    sa.Column('shipped_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prd_roadmap_items_workspace_id'), 'prd_roadmap_items', ['workspace_id'], unique=False)
    op.create_table('prd_feature_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='other', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='new', nullable=False),
    sa.Column('roadmap_item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['roadmap_item_id'], ['prd_roadmap_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prd_feature_requests_organization_id'), 'prd_feature_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_prd_feature_requests_roadmap_item_id'), 'prd_feature_requests', ['roadmap_item_id'], unique=False)
    op.create_index(op.f('ix_prd_feature_requests_workspace_id'), 'prd_feature_requests', ['workspace_id'], unique=False)
    op.create_table('prd_release_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=True),
    sa.Column('released_on', sa.Date(), nullable=True),
    sa.Column('roadmap_item_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_item_id'], ['prd_roadmap_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prd_release_notes_workspace_id'), 'prd_release_notes', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prd_release_notes_workspace_id'), table_name='prd_release_notes')
    op.drop_table('prd_release_notes')
    op.drop_index(op.f('ix_prd_feature_requests_workspace_id'), table_name='prd_feature_requests')
    op.drop_index(op.f('ix_prd_feature_requests_roadmap_item_id'), table_name='prd_feature_requests')
    op.drop_index(op.f('ix_prd_feature_requests_organization_id'), table_name='prd_feature_requests')
    op.drop_table('prd_feature_requests')
    op.drop_index(op.f('ix_prd_roadmap_items_workspace_id'), table_name='prd_roadmap_items')
    op.drop_table('prd_roadmap_items')
    # ### end Alembic commands ###
