"""department: people

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-26 12:56:20.384187
"""
from alembic import op
import sqlalchemy as sa


revision = '0011'
down_revision = '0010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ppl_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), server_default='contractor', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='onboarding', nullable=False),
    sa.Column('start_on', sa.Date(), nullable=True),
    sa.Column('end_on', sa.Date(), nullable=True),
    sa.Column('contract_document_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ppl_staff_person_id'), 'ppl_staff', ['person_id'], unique=False)
    op.create_index(op.f('ix_ppl_staff_workspace_id'), 'ppl_staff', ['workspace_id'], unique=False)
    op.create_table('ppl_access_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('account', sa.String(length=200), nullable=True),
    sa.Column('granted_on', sa.Date(), nullable=True),
    sa.Column('revoked_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['ppl_staff.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ppl_access_grants_staff_id'), 'ppl_access_grants', ['staff_id'], unique=False)
    op.create_index(op.f('ix_ppl_access_grants_workspace_id'), 'ppl_access_grants', ['workspace_id'], unique=False)
    op.create_table('ppl_checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('done', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('done_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['ppl_staff.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ppl_checklist_items_staff_id'), 'ppl_checklist_items', ['staff_id'], unique=False)
    op.create_index(op.f('ix_ppl_checklist_items_workspace_id'), 'ppl_checklist_items', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ppl_checklist_items_workspace_id'), table_name='ppl_checklist_items')
    op.drop_index(op.f('ix_ppl_checklist_items_staff_id'), table_name='ppl_checklist_items')
    op.drop_table('ppl_checklist_items')
    op.drop_index(op.f('ix_ppl_access_grants_workspace_id'), table_name='ppl_access_grants')
    op.drop_index(op.f('ix_ppl_access_grants_staff_id'), table_name='ppl_access_grants')
    op.drop_table('ppl_access_grants')
    op.drop_index(op.f('ix_ppl_staff_workspace_id'), table_name='ppl_staff')
    op.drop_index(op.f('ix_ppl_staff_person_id'), table_name='ppl_staff')
    op.drop_table('ppl_staff')
    # ### end Alembic commands ###
